version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env 
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
